import type { Property, ListingType, PropertyType } from "./types";

const px = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;

const img = (id: string, alt: string) => ({ url: px(id), alt, order: 1 });

/**
 * Seed inventory. Real production data lives in the database; this keeps the
 * platform fully functional out of the box and is merged alongside any data
 * submitted through the site's forms at runtime.
 */
export const seedProperties: Property[] = [
  {
    id: "p-001",
    title: "3 Bedroom House for Rent",
    slug: "3-bedroom-house-paynesville",
    type: "house",
    listingType: "rent",
    description:
      "A clean, well-laid-out 3-bedroom bungalow on a gated compound in Paynesville. Tiled floors throughout, a separate kitchen with storage, and a full bathroom with a second guest toilet. The compound has room for two cars plus a small garden — ideal for a young family that wants space without a big budget.",
    price: 650,
    currency: "USD",
    locationId: "paynesville",
    address: "Peace Walk, Paynesville, Liberia",
    bedrooms: 3,
    bathrooms: 2,
    size: 140,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["parking", "water_supply", "security", "compound", "tiled_floor", "separate_kitchen"],
    features: ["Gated compound", "Tiled floors everywhere", "Separate kitchen", "Guest toilet", "Small garden", "Plastered & painted recently"],
    rules: [
      "12-month rental term preferred",
      "First month + deposit required",
      "No subletting without landlord consent",
    ],
    landmarks: ["Paynesville Market — 8 min drive", "Red Light Junction — 12 min", "Main Boulevard — 5 min"],
    agentNotes:
      "I inspected this house myself and confirmed with the landlord that it is vacant and ready. The area is quiet and family-friendly.",
    availabilityStatus: "available",
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-28",
    status: "available",
    featured: true,
    images: [
      img("photo-1600585154340-be6161a56a0c", "3 bedroom house exterior in Paynesville"),
      { url: px("photo-1600607687939-ce8a6c25118c"), alt: "Living room with tiled floor", order: 2 },
      { url: px("photo-1600566753190-17f0baa2a6c3"), alt: "Bedroom interior", order: 3 },
      { url: px("photo-1554995207-c18c203602cb"), alt: "Kitchen with storage", order: 4 },
    ],
    createdAt: "2026-07-14",
    updatedAt: "2026-08-28",
  },
  {
    id: "p-002",
    title: "Spacious 4 Bedroom Compound for Family",
    slug: "spacious-4-bedroom-compound-sinkor",
    type: "compound",
    listingType: "rent",
    description:
      "A rare, large compound on the Sinkor side of Monrovia — four ensuite bedrooms, a big living area, fitted kitchen and generous outdoor space. Designed for families or professionals who need room to live and work. 24-hour security post at the gate.",
    price: 1200,
    currency: "USD",
    locationId: "sinkor",
    address: "Tubman Boulevard area, Sinkor, Monrovia",
    bedrooms: 4,
    bathrooms: 4,
    size: 260,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["parking", "generator", "water_supply", "security", "compound", "tiled_floor", "separate_kitchen", "servant_quarters"],
    features: ["Ensuite bedrooms", "Standby generator", "Inverter backup", "24h security", "Servant quarters", "Large compound"],
    rules: [
      "Family or corporate tenancy",
      "12-month term",
      "Security fee applies",
    ],
    landmarks: ["UN Drive — 6 min drive", "Tubman Boulevard — 4 min", "Airport road — 10 min"],
    agentNotes:
      "One of my favorite properties. The owner is serious about long-term tenants. Contact me for the viewing slot this week.",
    availabilityStatus: "available",
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-30",
    status: "available",
    featured: true,
    images: [
      img("photo-1512917774080-9991f1c4c750", "Family compound home in Sinkor"),
      { url: px("photo-1560448204-e02f11c3d0e2"), alt: "Open living room", order: 2 },
      { url: px("photo-1613490493576-7fde63acd811"), alt: "Master bedroom", order: 3 },
      { url: px("photo-1484154218962-a197022b5858"), alt: "Fitted kitchen", order: 4 },
    ],
    createdAt: "2026-06-02",
    updatedAt: "2026-08-30",
  },
  {
    id: "p-003",
    title: "2 Bedroom Apartment for Rent",
    slug: "2-bedroom-apartment-congo-town",
    type: "apartment",
    listingType: "rent",
    description:
      "A modern second-floor 2-bedroom apartment in a quiet Congo Town street. Open-plan living and dining, tiled throughout, with a balcony and dedicated parking below. Water supply and generator hours are well managed by the building.",
    price: 450,
    currency: "USD",
    locationId: "congo-town",
    address: "Jacob Street, Congo Town, Monrovia",
    bedrooms: 2,
    bathrooms: 1,
    size: 95,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["parking", "water_supply", "tiled_floor", "balcony"],
    features: ["Open-plan living", "Balcony", "Tiled floors", "Dedicated parking", "Water supply"],
    rules: [
      "6 or 12-month term",
      "Deposit required",
      "Pets negotiated with landlord",
    ],
    landmarks: ["Congo Town junction — 5 min", "Ducor area — 8 min", "Main market — 6 min"],
    agentNotes:
      "Recently checked — availability confirmed on my last visit. The building is clean and well managed.",
    availabilityStatus: "available",
    verificationStatus: "recently_checked",
    lastVerifiedAt: "2026-08-26",
    status: "available",
    featured: false,
    images: [
      img("photo-1522708323590-d24dbb6b0267", "Modern 2 bedroom apartment interior"),
      { url: px("photo-1502672260266-1c1ef2d93688"), alt: "Apartment bedroom", order: 2 },
      { url: px("photo-1502672023488-70e25813eb80"), alt: "Kitchen and dining area", order: 3 },
    ],
    createdAt: "2026-07-20",
    updatedAt: "2026-08-26",
  },
  {
    id: "p-004",
    title: "Room for Rent",
    slug: "room-for-rent-elwa",
    type: "room",
    listingType: "rent",
    description:
      "A clean, furnished single room in a shared house along the ELWA corridor. Includes a shared bathroom, common kitchen access, and running water. Perfect for students and young professionals starting out.",
    price: 120,
    currency: "USD",
    locationId: "elwa",
    address: "ELWA, Airport Highway, Liberia",
    bedrooms: 1,
    bathrooms: 1,
    furnished: true,
    amenities: ["water_supply", "security", "internet"],
    features: ["Furnished", "Shared kitchen", "Water supply", "Internet ready"],
    rules: [
      "Single occupancy",
      "Shared common areas",
      "Monthly rent in advance",
    ],
    landmarks: ["ELWA Junction — 3 min", "Airport road — 1 min", "Bus stop — 2 min walk"],
    agentNotes:
      "A genuine budget option. I confirmed the room is free and clean. Fast to secure.",
    availabilityStatus: "available",
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-29",
    status: "available",
    featured: false,
    images: [
      img("photo-1522708323590-d24dbb6b0267", "Simple furnished room"),
      { url: px("photo-1502672260266-1c1ef2d93688"), alt: "Bedroom view", order: 2 },
    ],
    createdAt: "2026-08-01",
    updatedAt: "2026-08-29",
  },
  {
    id: "p-005",
    title: "2 Bedroom House with Yard for Rent",
    slug: "2-bedroom-house-with-yard-brewerville",
    type: "house",
    listingType: "rent",
    description:
      "A practical 2-bedroom family house in Brewerville with a fenced yard, kitchen, and space for a car. Freshly painted with a reliable well-pump water system. Good value for families on a clear budget.",
    price: 500,
    currency: "USD",
    locationId: "brewerville",
    address: "Brewerville, Millsburg Road, Liberia",
    bedrooms: 2,
    bathrooms: 1,
    size: 110,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["parking", "water_supply", "compound", "tiled_floor", "separate_kitchen", "security"],
    features: ["Fenced yard", "Freshly painted", "Well water pump", "Parking", "Separate kitchen"],
    rules: ["12-month term", "Deposit", "Owner approval for modifications"],
    landmarks: ["Brewerville highway — 4 min", "Millsburg road — 2 min", "Market — 7 min"],
    agentNotes: "Family home, inspected recently. Landlord is approachable and flexible.",
    availabilityStatus: "available",
    verificationStatus: "recently_checked",
    lastVerifiedAt: "2026-08-24",
    status: "available",
    featured: false,
    images: [
      img("photo-1568605114967-8130f3a36994", "Two bedroom family house in Brewerville"),
      { url: px("photo-1570129477492-45c003edd2be"), alt: "House exterior with yard", order: 2 },
      { url: px("photo-1600607687939-ce8a6c25118c"), alt: "Living room", order: 3 },
    ],
    createdAt: "2026-07-05",
    updatedAt: "2026-08-24",
  },
  {
    id: "p-006",
    title: "Modern 2 Bedroom Apartment near UN Drive",
    slug: "modern-2-bedroom-apartment-un-drive-sinkor",
    type: "apartment",
    listingType: "rent",
    description:
      "Executive-grade 2-bedroom apartment minutes from UN Drive. Air-conditioned bedrooms, modern kitchen with fitted cabinets, ample water and standby generator. Comes with one parking slot in a secured compound.",
    price: 800,
    currency: "USD",
    locationId: "sinkor",
    address: "Windward, Sinkor, Monrovia",
    bedrooms: 2,
    bathrooms: 2,
    size: 125,
    sizeUnit: "m²",
    furnished: true,
    amenities: ["parking", "generator", "water_supply", "security", "air_conditioning", "tiled_floor", "internet", "furnished"],
    features: ["Air conditioning", "Furnished", "Standby generator", "Fitted kitchen", "Dedicated parking"],
    rules: ["12-month corporate or family term", "Security deposit", "Generator fee applicable"],
    landmarks: ["UN Drive — 5 min", "Embassies — 8 min", "Airport road — 12 min"],
    agentNotes: "Premium option for executives. Ask me about the short-stay corporate rate.",
    availabilityStatus: "available",
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-30",
    status: "available",
    featured: true,
    images: [
      img("photo-1493809842364-78817add7ffb", "Executive apartment living room"),
      { url: px("photo-1493663284031-b7e3aefcae8e"), alt: "Modern living space", order: 2 },
      { url: px("photo-1484101403633-562f891dc89a"), alt: "Apartment interior", order: 3 },
      { url: px("photo-1556912173-3bb406ef7e77"), alt: "Kitchen", order: 4 },
    ],
    createdAt: "2026-05-10",
    updatedAt: "2026-08-30",
  },
  {
    id: "p-007",
    title: "5 Bedroom House for Sale",
    slug: "5-bedroom-house-for-sale-sinkor",
    type: "house",
    listingType: "buy",
    description:
      "A substantial 5-bedroom house for sale in a desirable Sinkor location. Spacious rooms, large living areas, servant quarters and a compound with parking for several vehicles. Documentation being reviewed with the owner; serious buyers only.",
    price: 180000,
    currency: "USD",
    locationId: "sinkor",
    address: "Sinkor, Monrovia, Liberia",
    bedrooms: 5,
    bathrooms: 4,
    size: 320,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["parking", "generator", "security", "compound", "tiled_floor", "separate_kitchen", "servant_quarters"],
    features: ["5 bedrooms", "Servant quarters", "Large compound", "Multiple parking", "Tiled throughout"],
    rules: [
      "Title documentation review with agent",
      "Serious buyer requirement",
      "Payment structure negotiable",
    ],
    landmarks: ["Sinkor business district — 6 min", "UN Drive — 8 min"],
    agentNotes:
      "Privacy respected — I will only arrange viewings after an initial conversation with me.",
    availabilityStatus: "available",
    verificationStatus: "owner_submitted",
    lastVerifiedAt: "2026-08-22",
    status: "available",
    featured: false,
    images: [
      img("photo-1600596542815-ffad4c1539a9", "Large family house for sale"),
      { url: px("photo-1564013799919-ab600027ffc6"), alt: "Spacious home exterior", order: 2 },
      { url: px("photo-1600566753086-00f18fb6b3ea"), alt: "Interior living space", order: 3 },
    ],
    createdAt: "2026-06-18",
    updatedAt: "2026-08-22",
  },
  {
    id: "p-008",
    title: "Prime Commercial Space",
    slug: "prime-commercial-space-monrovia",
    type: "commercial",
    listingType: "rent",
    description:
      "High-visibility commercial space in downtown Monrovia with main-road frontage, customer parking and a second level. Ideal for a bank, restaurant, retail anchor or professional office.",
    price: 1500,
    currency: "USD",
    locationId: "monrovia",
    address: "Carey Street, Monrovia",
    bedrooms: 0,
    bathrooms: 2,
    size: 180,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["parking", "security", "water_supply", "air_conditioning"],
    features: ["Main-road frontage", "Customer parking", "Two levels", "High foot traffic"],
    rules: ["Commercial lease terms", "Fit-out approved by landlord"],
    landmarks: ["Central Monrovia business district", "Crossroads of major streets"],
    agentNotes: "Great spot for a serious business. Let me know your sector.",
    availabilityStatus: "available",
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-27",
    status: "available",
    featured: false,
    images: [
      img("photo-1486406146926-c627a92ad1ab", "Commercial building frontage"),
      { url: px("photo-1497366754035-f200968a6e72"), alt: "Office interior space", order: 2 },
      { url: px("photo-1497366811353-6870744d04b2"), alt: "Commercial workspace", order: 3 },
    ],
    createdAt: "2026-07-01",
    updatedAt: "2026-08-27",
  },
  {
    id: "p-009",
    title: "Land for Sale",
    slug: "land-for-sale-brewerville",
    type: "land",
    listingType: "buy",
    description:
      "A clean, well-located residential lot in Brewerville, suitable for a family house or a small compound project. Road access is in place; I will help you review the deed and survey before any commitment.",
    price: 25000,
    currency: "USD",
    locationId: "brewerville",
    address: "Brewerville, Liberia",
    bedrooms: 0,
    bathrooms: 0,
    size: 1200,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["security"],
    features: ["Road access", "Deed & survey review", "Residential zoning"],
    rules: ["Deed and survey review before commitment", "Buyer responsible for transfer fees by agreement"],
    landmarks: ["Brewerville highway — 3 min", "Community road — roadside"],
    agentNotes: "Documentation verified structurally. Confirm ownership chain before closing.",
    availabilityStatus: "available",
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-25",
    status: "available",
    featured: false,
    images: [
      img("photo-1500382017468-9049fed747ef", "Land lot in Brewerville"),
      { url: px("photo-1500076656116-558758c991c1"), alt: "Open land parcel", order: 2 },
    ],
    createdAt: "2026-05-22",
    updatedAt: "2026-08-25",
  },
  {
    id: "p-010",
    title: "Land for Sale",
    slug: "land-for-sale-rehab",
    type: "land",
    listingType: "buy",
    description:
      "Residential land in Rehab with a calm, family-oriented neighborhood. Enough space for a 3 to 4-bedroom house plus parking. Ideal for first-time buyers building gradually.",
    price: 18000,
    currency: "USD",
    locationId: "rehab",
    address: "Rehab, Liberia",
    bedrooms: 0,
    bathrooms: 0,
    size: 900,
    sizeUnit: "m²",
    furnished: false,
    amenities: [],
    features: ["Road access", "Family neighborhood", "Build gradually"],
    rules: ["Deed review", "Survey confirmation"],
    landmarks: ["Rehab junction — 4 min", "Paynesville central — 12 min"],
    agentNotes: "Been checking land values in Rehab — this is priced fairly for the location.",
    availabilityStatus: "available",
    verificationStatus: "recently_checked",
    lastVerifiedAt: "2026-08-23",
    status: "available",
    featured: false,
    images: [
      img("photo-1500382017468-9049fed747ef", "Land in Rehab for sale"),
    ],
    createdAt: "2026-07-28",
    updatedAt: "2026-08-23",
  },
  {
    id: "p-011",
    title: "Furnished Studio — Short Stay",
    slug: "furnished-studio-short-stay-sinkor",
    type: "short-term",
    listingType: "short-term",
    description:
      "A fully furnished studio in Sinkor for short stays — whether you're between homes, on a work trip, or returning to Liberia and looking for a base while you search. Water, generator and security included. Daily and weekly rates.",
    price: 80,
    currency: "USD",
    locationId: "sinkor",
    address: "Sinkor, Monrovia",
    bedrooms: 1,
    bathrooms: 1,
    size: 45,
    sizeUnit: "m²",
    furnished: true,
    amenities: ["furnished", "generator", "water_supply", "security", "air_conditioning", "internet"],
    features: ["Fully furnished", "Air conditioning", "Internet", "Daily/weekly rates", "All bills handled"],
    rules: ["Minimum 3 nights", "ID required", "Full payment in advance"],
    landmarks: ["UN Drive — 5 min", "Sinkor business area — 6 min"],
    agentNotes: "Great stopgap option while house-hunting. I often recommend this to clients between homes.",
    availabilityStatus: "available",
    verificationStatus: "verified",
    lastVerifiedAt: "2026-08-29",
    status: "available",
    featured: false,
    images: [
      img("photo-1502672023488-70e25813eb80", "Furnished studio apartment"),
      { url: px("photo-1522708323590-d24dbb6b0267"), alt: "Studio interior", order: 2 },
    ],
    createdAt: "2026-08-02",
    updatedAt: "2026-08-29",
  },
  {
    id: "p-012",
    title: "6 Bedroom Compound for Sale",
    slug: "6-bedroom-compound-for-sale-new-georgia",
    type: "compound",
    listingType: "buy",
    description:
      "An entire family compound for sale in New Georgia — six bedrooms across two wings, separate kitchen, servant quarters and a deep fenced yard. A strong purchase for a family or an investor converting to rental income.",
    price: 120000,
    currency: "USD",
    locationId: "new-georgia",
    address: "New Georgia, Liberia",
    bedrooms: 6,
    bathrooms: 4,
    size: 400,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["parking", "water_supply", "security", "compound", "tiled_floor", "separate_kitchen", "servant_quarters", "generator"],
    features: ["Two wings", "Servant quarters", "Fenced yard", "Income potential", "Parking"],
    rules: ["Serious buyers", "Documentation review", "Viewing after initial call"],
    landmarks: ["New Georgia road — 3 min", "Community market — 6 min"],
    agentNotes: "Strong rental-income play if you don't need all six bedrooms.",
    availabilityStatus: "available",
    verificationStatus: "owner_submitted",
    lastVerifiedAt: "2026-08-20",
    status: "available",
    featured: false,
    images: [
      img("photo-1570129477492-45c003edd2be", "Family compound for sale"),
      { url: px("photo-1600047509807-ba8f99d2cdde"), alt: "Compound with yard", order: 2 },
      { url: px("photo-1600596542815-ffad4c1539a9"), alt: "House exterior", order: 3 },
    ],
    createdAt: "2026-06-25",
    updatedAt: "2026-08-20",
  },
  {
    id: "p-013",
    title: "Office Space in Association Area",
    slug: "office-space-congo-town",
    type: "office",
    listingType: "rent",
    description:
      "A professional office space in the Congo Town association area with security, parking and reliable power. Two rooms plus a reception area — ready for a law office, consultancy or NGO team.",
    price: 850,
    currency: "USD",
    locationId: "congo-town",
    address: "Association area, Congo Town",
    bedrooms: 0,
    bathrooms: 1,
    size: 70,
    sizeUnit: "m²",
    furnished: false,
    amenities: ["parking", "security", "water_supply", "generator", "internet"],
    features: ["Two offices + reception", "Reliable power", "Parking", "Secure compound"],
    rules: ["12-month office lease", "Interior fit-out allowed"],
    landmarks: ["Congo Town junction — 5 min", "Business corridor — 4 min"],
    agentNotes: "Good for a small professional team. Generator hours shared with building.",
    availabilityStatus: "available",
    verificationStatus: "recently_checked",
    lastVerifiedAt: "2026-08-27",
    status: "available",
    featured: false,
    images: [
      img("photo-1497366811353-6870744d04b2", "Office space interior"),
      { url: px("photo-1431540015161-0bf868a2d407"), alt: "Office room", order: 2 },
    ],
    createdAt: "2026-08-05",
    updatedAt: "2026-08-27",
  },
];

export const propertyTypeOptions: { value: string; label: string }[] = [
  { value: "house", label: "House" },
  { value: "room", label: "Room" },
  { value: "apartment", label: "Apartment" },
  { value: "compound", label: "Compound" },
  { value: "office", label: "Office Space" },
  { value: "commercial", label: "Commercial Space" },
  { value: "land", label: "Land" },
  { value: "short-term", label: "Short-Term Stay" },
];

export const amenityLabels: Record<string, string> = {
  parking: "Parking",
  generator: "Generator",
  water_supply: "Water Supply",
  security: "Security",
  compound: "Compound",
  tiled_floor: "Tiled Floor",
  air_conditioning: "Air Conditioning",
  internet: "Internet",
  separate_kitchen: "Separate Kitchen",
  servant_quarters: "Servant Quarters",
  furnished: "Furnished",
  balcony: "Balcony",
  inverter: "Inverter",
};

export const typeLabels: Record<PropertyType, string> = {
  house: "House",
  room: "Room",
  apartment: "Apartment",
  compound: "Compound",
  office: "Office Space",
  commercial: "Commercial Space",
  land: "Land",
  "short-term": "Short-Term Stay",
};

/** PropertyType → clean URL segment used in /rent/* and /buy/* routes */
export const propertyTypeMap: Record<PropertyType, string> = {
  house: "houses",
  room: "rooms",
  apartment: "apartments",
  compound: "compounds",
  office: "offices",
  commercial: "commercial",
  land: "land",
  "short-term": "short-term",
};

export const listingLabels: Record<ListingType, string> = {
  rent: "For Rent",
  buy: "For Sale",
  "short-term": "Short Stay",
};

export const listingNoun: Record<ListingType, string> = {
  rent: "Rent",
  buy: "Sale",
  "short-term": "Stay",
};

export const verificationLabels: Record<
  Property["verificationStatus"],
  { label: string; description: string }
> = {
  verified: {
    label: "Verified",
    description: "Property information and availability personally confirmed.",
  },
  recently_checked: {
    label: "Recently Checked",
    description: "Recently contacted/visited and availability confirmed.",
  },
  owner_submitted: {
    label: "Owner Submitted",
    description: "Submitted by owner but not yet verified.",
  },
  unavailable: {
    label: "Unavailable",
    description: "No longer available.",
  },
};

export const requestStatusLabels: Record<string, string> = {
  new: "New",
  searching: "Searching",
  matches_found: "Matches Found",
  viewing_scheduled: "Viewing Scheduled",
  closed: "Closed",
};

export const leadStageLabels: Record<string, string> = {
  new: "New",
  contacted: "Contacted",
  viewing: "Viewing",
  negotiation: "Negotiation",
  closed: "Closed",
  lost: "Lost",
};